package com.huawei.esdk.csdemo.soap.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2015-01-27T19:31:56.771+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "http://smc.huawei.com/", name = "TPProfessional.SiteMgr")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TPProfessionalSiteMgr {

    @WebResult(name = "setAuxStreamExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/setAuxStreamEx")
    public SetAuxStreamExResponse setAuxStreamEx(
        @WebParam(partName = "parameters", name = "setAuxStreamEx", targetNamespace = "http://smc.huawei.com/")
        SetAuxStreamEx parameters
    );

    @WebResult(name = "querySitesInfoExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/querySitesInfoEx")
    public QuerySitesInfoExResponse querySitesInfoEx(
        @WebParam(partName = "parameters", name = "querySitesInfoEx", targetNamespace = "http://smc.huawei.com/")
        QuerySitesInfoEx parameters
    );

    @WebResult(name = "ctrlCameraExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/ctrlCameraEx")
    public CtrlCameraExResponse ctrlCameraEx(
        @WebParam(partName = "parameters", name = "ctrlCameraEx", targetNamespace = "http://smc.huawei.com/")
        CtrlCameraEx parameters
    );

    @WebResult(name = "queryVideoOutSrcStateExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/queryVideoOutSrcStateEx")
    public QueryVideoOutSrcStateExResponse queryVideoOutSrcStateEx(
        @WebParam(partName = "parameters", name = "queryVideoOutSrcStateEx", targetNamespace = "http://smc.huawei.com/")
        QueryVideoOutSrcStateEx parameters
    );

    @WebResult(name = "setMainAuxStreamSourcesExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/setMainAuxStreamSourcesEx")
    public SetMainAuxStreamSourcesExResponse setMainAuxStreamSourcesEx(
        @WebParam(partName = "parameters", name = "setMainAuxStreamSourcesEx", targetNamespace = "http://smc.huawei.com/")
        SetMainAuxStreamSourcesEx parameters
    );

    @WebResult(name = "queryMainStreamSourcesExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/queryMainStreamSourcesEx")
    public QueryMainStreamSourcesExResponse queryMainStreamSourcesEx(
        @WebParam(partName = "parameters", name = "queryMainStreamSourcesEx", targetNamespace = "http://smc.huawei.com/")
        QueryMainStreamSourcesEx parameters
    );

    @WebResult(name = "isReceiveRemAuxStrmExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/isReceiveRemAuxStrmEx")
    public IsReceiveRemAuxStrmExResponse isReceiveRemAuxStrmEx(
        @WebParam(partName = "parameters", name = "isReceiveRemAuxStrmEx", targetNamespace = "http://smc.huawei.com/")
        IsReceiveRemAuxStrmEx parameters
    );

    @WebResult(name = "deleteSiteInfoExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/deleteSiteInfoEx")
    public DeleteSiteInfoExResponse deleteSiteInfoEx(
        @WebParam(partName = "parameters", name = "deleteSiteInfoEx", targetNamespace = "http://smc.huawei.com/")
        DeleteSiteInfoEx parameters
    );

    @WebResult(name = "editSiteInfoExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/editSiteInfoEx")
    public EditSiteInfoExResponse editSiteInfoEx(
        @WebParam(partName = "parameters", name = "editSiteInfoEx", targetNamespace = "http://smc.huawei.com/")
        EditSiteInfoEx parameters
    );

    @WebResult(name = "addSiteInfoExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/addSiteInfoEx")
    public AddSiteInfoExResponse addSiteInfoEx(
        @WebParam(partName = "parameters", name = "addSiteInfoEx", targetNamespace = "http://smc.huawei.com/")
        AddSiteInfoEx parameters
    );

    @WebResult(name = "isSendAuxStreamExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/isSendAuxStreamEx")
    public IsSendAuxStreamExResponse isSendAuxStreamEx(
        @WebParam(partName = "parameters", name = "isSendAuxStreamEx", targetNamespace = "http://smc.huawei.com/")
        IsSendAuxStreamEx parameters
    );

    @WebResult(name = "setVideoOutSrcExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/setVideoOutSrcEx")
    public SetVideoOutSrcExResponse setVideoOutSrcEx(
        @WebParam(partName = "parameters", name = "setVideoOutSrcEx", targetNamespace = "http://smc.huawei.com/")
        SetVideoOutSrcEx parameters
    );

    @WebResult(name = "queryAuxStreamSourcesExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/queryAuxStreamSourcesEx")
    public QueryAuxStreamSourcesExResponse queryAuxStreamSourcesEx(
        @WebParam(partName = "parameters", name = "queryAuxStreamSourcesEx", targetNamespace = "http://smc.huawei.com/")
        QueryAuxStreamSourcesEx parameters
    );

    @WebResult(name = "querySiteVersionInfoExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/querySiteVersionInfoEx")
    public QuerySiteVersionInfoExResponse querySiteVersionInfoEx(
        @WebParam(partName = "parameters", name = "querySiteVersionInfoEx", targetNamespace = "http://smc.huawei.com/")
        QuerySiteVersionInfoEx parameters
    );

    @WebResult(name = "isConnectAuxSourceExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/isConnectAuxSourceEx")
    public IsConnectAuxSourceExResponse isConnectAuxSourceEx(
        @WebParam(partName = "parameters", name = "isConnectAuxSourceEx", targetNamespace = "http://smc.huawei.com/")
        IsConnectAuxSourceEx parameters
    );
}
