package com.huawei.esdk.csdemo.soap.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2015-01-27T19:31:56.787+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "http://smc.huawei.com/", name = "TPProfessional.TerminalConfCtr")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TPProfessionalTerminalConfCtr {

    @WebResult(name = "requestChairExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/requestChairEx")
    public RequestChairExResponse requestChairEx(
        @WebParam(partName = "parameters", name = "requestChairEx", targetNamespace = "http://smc.huawei.com/")
        RequestChairEx parameters
    );

    @WebResult(name = "releaseChairExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/releaseChairEx")
    public ReleaseChairExResponse releaseChairEx(
        @WebParam(partName = "parameters", name = "releaseChairEx", targetNamespace = "http://smc.huawei.com/")
        ReleaseChairEx parameters
    );

    @WebResult(name = "setDirectBroadExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/setDirectBroadEx")
    public SetDirectBroadExResponse setDirectBroadEx(
        @WebParam(partName = "parameters", name = "setDirectBroadEx", targetNamespace = "http://smc.huawei.com/")
        SetDirectBroadEx parameters
    );

    @WebResult(name = "setRecordBroadExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/setRecordBroadEx")
    public SetRecordBroadExResponse setRecordBroadEx(
        @WebParam(partName = "parameters", name = "setRecordBroadEx", targetNamespace = "http://smc.huawei.com/")
        SetRecordBroadEx parameters
    );

    @WebResult(name = "queryBroadInfoExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/queryBroadInfoEx")
    public QueryBroadInfoExResponse queryBroadInfoEx(
        @WebParam(partName = "parameters", name = "queryBroadInfoEx", targetNamespace = "http://smc.huawei.com/")
        QueryBroadInfoEx parameters
    );

    @WebResult(name = "queryConfCtrlPwdExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/queryConfCtrlPwdEx")
    public QueryConfCtrlPwdExResponse queryConfCtrlPwdEx(
        @WebParam(partName = "parameters", name = "queryConfCtrlPwdEx", targetNamespace = "http://smc.huawei.com/")
        QueryConfCtrlPwdEx parameters
    );
}
