package com.huawei.esdk.csdemo.soap.impl.autogen;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2015-01-27T19:31:56.601+08:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "http://smc.huawei.com/", name = "TPProfessional.MCUMgr")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TPProfessionalMCUMgr {

    @WebResult(name = "queryMCUFutureResourceExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/queryMCUFutureResourceEx")
    public QueryMCUFutureResourceExResponse queryMCUFutureResourceEx(
        @WebParam(partName = "parameters", name = "queryMCUFutureResourceEx", targetNamespace = "http://smc.huawei.com/")
        QueryMCUFutureResourceEx parameters
    );

    @WebResult(name = "queryMCUInfoExResponse", targetNamespace = "http://smc.huawei.com/", partName = "parameters")
    @WebMethod(action = "http://smc.huawei.com/queryMCUInfoEx")
    public QueryMCUInfoExResponse queryMCUInfoEx(
        @WebParam(partName = "parameters", name = "queryMCUInfoEx", targetNamespace = "http://smc.huawei.com/")
        QueryMCUInfoEx parameters
    );
}
